default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  username: <%= ENV["PG_USER"] || "postgres" %>

development:
  <<: *default
  database: rails_example_development

test:
  <<: *default
  database: rails_example_test
